import { Nunito } from 'next/font/google';
import Navbar from './components/navbar/Navbar';
import type { Metadata } from 'next';
import './globals.css';
import ClientOnly from './components/ClientOnly';
import Modal from './components/modals/Modal';
import RegisterModal from './components/modals/RegisterModal';
import { Toaster } from 'react-hot-toast';
import LoginModal from './components/modals/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
import RentModal from './components/modals/RentModal';

export const metadata: Metadata = {
	title: 'Airbnb',
	description: 'Generated by create next app'
};

const font = Nunito({
	subsets: ['latin']
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const currentUser = await getCurrentUser();
	return (
		<html lang="en">
			<body className={font.className}>
				<ClientOnly>
					<Toaster />
					<RentModal />
					<RegisterModal />
					<LoginModal />
					<Navbar currentUser={currentUser} />
				</ClientOnly>
				<div className="pb-20 pt-28">{children}</div>
			</body>
		</html>
	);
}
